version: '2'
services:
  mitmproxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: ["mitmdump", "--server-replay", "scripts/locust.bin", "--no-server-replay-refresh", "--server-replay-kill-extra", "--set upstream_cert=false", "--server-replay-nopop"]
    ports:
      - "8080"

networks:
  default:
    external:
      name: backend_default